#!/usr/bin/env python3
"""regrade_json.py — execution-aware reclassification of existing primitives_lab JSONs.

Reads result files from results/, applies execution-aware scoring retroactively
(every dispatched tool_call must have ok=true), and emits a markdown comparison
table pre/post per variant.

This is NOT a re-run — it's a re-classification of already-captured data. The
underlying JSON files must contain execution_results per sample for this to work.
If any sample lacks execution_results, it's marked regrade_partial.

Output:
  - <input>.regraded.json (sibling file with `regraded_passed` field per sample)
  - stdout markdown table

Usage:
  python regrade_json.py results/001-*.json results/004-*.json ...
"""
import argparse
import json
import sys
from pathlib import Path


def regrade_sample(sample: dict) -> tuple[bool, list[str], bool]:
    """Apply execution-aware scoring. Returns (regraded_passed, failures, was_partial)."""
    failures = list(sample.get("failures") or [])

    # If sample has policy_handled / outcome fields, respect them
    if sample.get("outcome") == "policy_handled_upstream":
        # Already triaged correctly by post-patch runner
        return (not failures), failures, False

    # Otherwise: check execution_results
    exec_results = sample.get("execution_results")
    if exec_results is None:
        # Field was not captured by old runner; can only echo original passed
        return sample.get("passed", False), failures, True

    failed = [er for er in exec_results if not er.get("ok")]
    if failed:
        err_types = sorted({er.get("error_type", "unknown") for er in failed})
        excerpts = [(er.get("details") or "")[:80] for er in failed[:3]]
        failures.append(
            f"bot_execution_failed: {len(failed)}/{len(exec_results)} tool_calls ok=false "
            f"(error_types={err_types}; first details: {excerpts})"
        )
        return False, failures, False

    return (not failures), failures, False


def regrade_file(path: Path) -> dict:
    """Regrade one result JSON. Returns summary dict."""
    data = json.loads(path.read_text())
    spec_id = data.get("spec", {}).get("id", "?")
    per_variant = []
    file_partial = False

    for variant in data.get("results", []):
        v_id = variant.get("id")
        samples = variant.get("samples", [])
        orig_pass = sum(1 for s in samples if s.get("passed"))
        regraded_pass = 0
        partial_in_variant = 0
        for s in samples:
            new_passed, new_failures, was_partial = regrade_sample(s)
            s["regraded_passed"] = new_passed
            s["regraded_failures"] = new_failures
            s["regrade_partial"] = was_partial
            if was_partial:
                partial_in_variant += 1
                file_partial = True
            if new_passed:
                regraded_pass += 1
        per_variant.append({
            "variant": v_id,
            "n": len(samples),
            "orig_pass": orig_pass,
            "regraded_pass": regraded_pass,
            "partial_samples": partial_in_variant,
        })

    out_path = path.with_suffix(".regraded.json")
    out_path.write_text(json.dumps(data, indent=2))

    return {
        "file": path.name,
        "spec_id": spec_id,
        "per_variant": per_variant,
        "any_partial": file_partial,
        "regraded_path": out_path,
    }


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("paths", nargs="+", type=Path)
    p.add_argument("--md-output", type=Path, help="optional path to write markdown table to a file")
    args = p.parse_args()

    summaries = []
    for path in args.paths:
        if not path.exists():
            print(f"[warn] not found: {path}", file=sys.stderr)
            continue
        summaries.append(regrade_file(path))

    # Markdown output
    lines = []
    lines.append("# Baseline regraded — execution-aware (svc-OK) scoring")
    lines.append("")
    lines.append(f"Generated by `regrade_json.py` on {sum(s['per_variant'].__len__() for s in summaries)} variants across {len(summaries)} result files.")
    lines.append("")
    lines.append("**Methodology**: each sample re-graded with the new rule "
                 "`require_bot_execution=True` (default): every entry in `execution_results` must have `ok=true` for the sample to PASS. Original `passed` field is preserved; new field `regraded_passed` reflects the corrected scoring.")
    lines.append("")
    lines.append("If a sample's source JSON lacks `execution_results`, that sample is marked `regrade_partial: true` and its `regraded_passed` falls back to the original `passed` value (since we can't re-evaluate without the bot's ok flags).")
    lines.append("")
    lines.append("## Per-variant pre/post")
    lines.append("")
    lines.append("| Experiment | Variant | n | Orig pass | Regraded pass (svc-aware) | Δ | Partial? |")
    lines.append("|---|---|---|---|---|---|---|")
    for summary in summaries:
        for v in summary["per_variant"]:
            delta = v["regraded_pass"] - v["orig_pass"]
            partial = f"⚠️ {v['partial_samples']}/{v['n']}" if v["partial_samples"] > 0 else ""
            lines.append(
                f"| {summary['spec_id']} | {v['variant']} | {v['n']} | "
                f"{v['orig_pass']}/{v['n']} | {v['regraded_pass']}/{v['n']} | "
                f"{delta:+d} | {partial} |"
            )
    lines.append("")
    lines.append("## Files regraded")
    lines.append("")
    for s in summaries:
        lines.append(f"- `{s['file']}` → `{s['regraded_path'].name}`")
    lines.append("")
    lines.append("## Interpretación")
    lines.append("")
    lines.append("Lecturas relevantes:")
    lines.append("- **Δ negativos grandes** (≥-3) = el variant tenía PASS espurios; el bot soft-failed pero el runner no lo capturaba. Casos canónicos: `toss_apple` (auto-pickup), `eat_food` (food=20), `equip_torch` (chains incoherentes).")
    lines.append("- **Δ = 0** = la primitiva ya funcionaba a nivel ejecución; el runner reportaba bien.")
    lines.append("- **Partial** = sample sin `execution_results` capturado; el regrade lo echó atrás al original. Tipicamente algo de runs antiguos.")
    out = "\n".join(lines)
    print(out)

    if args.md_output:
        args.md_output.write_text(out + "\n")
        print(f"\n[regrade] markdown saved to: {args.md_output}", file=sys.stderr)


if __name__ == "__main__":
    main()
